notifications:
  slack: $slack
sudo: required
language: node_js
node_js:
    - "9.7.1"
install:
  - npm i
script:
  - npx ng lint
  - npx ng test @angeeks/md --watch=false
  - npx ng build @angeeks/md --prod
  - npx ng test marked --watch=false
  - npx ng build marked --prod --base-href marked
cache:
    directories:
      - node_modules
deploy:
  - provider: pages
    local-dir: dist/marked
    github-token: $github
    skip-cleanup: true
    keep-history: true
